### ISSUE TITLE
Can't access the readme on Windows under MSYS2

### ISSUE THREAD

**Issue by miv-ableton** [ipfs/support#11]
Just downloaded and installed the amd64 release of ipfs. I ran ipfs init and got:

```
$ ipfs init
initializing ipfs node at C:\Users\miv\.ipfs
generating 2048-bit RSA keypair...done
peer identity: QmUHCb7PayEdp2TmKLjnUBc96o3WPDaowEEzw1WbwvGyB6
to get started, enter:

        ipfs cat /ipfs/QmVtU7ths96fMgZ8YSZAbKghyieq7AjxNdcqyVzxTt3qVe/readme
```

Then I copy and pasted the command and got:

```
$ ipfs cat /ipfs/QmVtU7ths96fMgZ8YSZAbKghyieq7AjxNdcqyVzxTt3qVe/readme
Error: invalid ipfs ref path
```

I tried it again and got:

```
$ ipfs cat /ipfs/QmVtU7ths96fMgZ8YSZAbKghyieq7AjxNdcqyVzxTt3qVe/readme
Error: can't Lock file "C:\\Users\\miv\\.ipfs/repo.lock": has non-zero size
```

It then alternates between these two errors. I'm using MSYS2. Does ipfs for Windows require cygwin or something instead? I have no idea what's going on.

**Comment by deawar** [comment]
Just to be thorough...did you include the ipfs directory in your environment path? This is an easy thing to overlook and as easy to fix.

**Comment by jbenet** [comment]
Cc @mithgol @gatesvp for windows wizardry

**Comment by Mithgol** [comment]
IPFS for Windows does not require cygwin.

The command `ipfs cat /ipfs/QmVtU7ths96fMgZ8YSZAbKghyieq7AjxNdcqyVzxTt3qVe/readme` works for me with the version of IPFS unpacked from https://gobuilder.me/get/github.com/ipfs/go-ipfs/cmd/ipfs/ipfs_v0.3.9_windows-amd64.zip

**Comment by Mithgol** [comment]
@miv-ableton You should probably try running IPFS on Windows directly (i.e. without using MSYS2, which is a Cygwin-derived software distro for Windows using Arch Linux's Pacman). Windows version of IPFS does not need Cygwin's API compatibility layer providing some part of the POSIX API functionality.

**Comment by miv-ableton** [comment]
Thank you! It appears that ipfs has these strange problems when run under MSYS2. Running it on a regular Windows cmd prompt fixed all the problems.

**Comment by jbenet** [comment]
Thanks @Mithgol and @miv-ableton!
