### ISSUE TITLE
[Bug] Error: resource temporarily unavailable

### ISSUE THREAD

**Issue by jbenet** [ipfs/support#12]
Moved from: https://github.com/ipfs/ipfs/issues/135

@karv said:

> Had been trying ipfs, everything was going well,
> I was about to connect to my other computer but suddenly the daemon crashed, i wanted to restart it but...
> 
> ```
> $ ipfs daemon
> Initializing daemon...
> Error: resource temporarily unavailable
> ```
> 
> OS: Ubuntu 15.10 64 bits
> ipfs version 0.3.10-dev (prebuilt)

**Comment by jbenet** [comment]
@karv said:

> Must add, happened after an ipfs ls command.

**Comment by jbenet** [comment]
@whyrusleeping said:

> how did it crash? what happened?

**Comment by jbenet** [comment]
i think there's a lock file lingering. this will get better in the near future, but if no other ipfs process is running, it's safe to remove the lock file:

``` sh
rm ~/.ipfs/repo.lock
# or wherever your repo is located.
```

if this _doesn't_ fix it immediately, post back here. it will be the leveldb lock that's lingering -- this one can be remove too:

``` sh
rm ~/.ipfs/datastore/LOCK
```

if this doesn't fix it, post back here. if it does, please close the issue. thanks!

**Comment by karv** [comment]
I've been trying this weekend and haven't been able to reproduce the result, even with the lock.
Maybe it is something about my configuration on Ubuntu, or I don't know?

**Comment by peteygao** [comment]
I ran into this issue just now, and removing both of the two lock file cleared up the issue (removing just the `repo.lock` file was actually insufficient). Thanks @jbenet!

**Comment by jbenet** [comment]
We should have a fix for this, like `ipfs repo repair` or `ipfs repo fsck` should make sure to do it.

**Comment by RichardLitt** [comment]
Reopen as needed!
