### ISSUE TITLE
Unable to retrieve files via gateway.ipfs.io

### ISSUE THREAD

**Issue by adamc199** [ipfs/support#15]
I believe my install is working correctly, I see a list of peers when I execute swarm peers

However, when attempting to retrieve a file I have added as demo'd in the video through gateway.ipfs.io/ipfs/QmTrgQg3TeuqNCqq85Q42x3rnER9eN96J5wj9C2yVD4rwv

The server just sits with a 'Waiting for gateway.ipfs.io" message.

Not sure where to start debugging my problem.

**Comment by fazo96** [comment]
> when attempting to retrieve a file I have added as demo'd in the video through gateway.ipfs.io/ipfs/QmTrgQg3TeuqNCqq85Q42x3rnER9eN96J5wj9C2yVD4rwv

What do you mean? How are you retreiving the file? That is an HTTP url, the associated IPFS address is `/ipfs/QmTrgQg3TeuqNCqq85Q42x3rnER9eN96J5wj9C2yVD4rwv`

**Comment by adamc199** [comment]
I was under the impression that you can test if your file has propagated throughout the network by retrieving it from the gateway.ipfs.io server. That is exactly what the video showed.
I am aple to retrieve files locally with ipfs get, but any other nide I has cannot retrieve my files.
I have a good number of peers when I execute ipfs swarm peers, but otherwise no joy.
How do I test to see if my install is functioning properly?

**Comment by lidel** [comment]
Are you running the same version as the Gateway?
https://gateway.ipfs.io/api/v0/version is "0.3.11"

**Comment by adamc199** [comment]
Thanks for responding. I set up an additional mode on an Amazon ec2 instance and I was able to retrieve files from my local laptop install and vice versa. So it works!  

What confused me was the demo video on ipfs.io 

It showed different results through gateway.ipfs.io and I was expecting my files to be available through their gateway.

**Comment by fazo96** [comment]
The files should be available through their gateway! Or any other gateway. Sometimes it just takes a few minutes for them to propagate the first time.

**Comment by jbenet** [comment]
It's likely a nat problem. we're aware of it.

**Comment by adamc199** [comment]
hmmm. Yet was unable to find a bug report for NAT in the tracker.

**Comment by RichardLitt** [comment]
@adamc199 We're actively working on fixing this right now. Do you still have this problem?

**Comment by adamc199** [comment]
This appears to have been fixed on the 4.x releases. 

AC

——————————————
K5ACC

Governments are reading your email. 
Slow them down with encryption.

My public key: pubkey.curry.com
——————————————

**Comment by RichardLitt** [comment]
Woo! :D

**Comment by RichardLitt** [comment]
Reopen as needed. Thanks!

**Comment by ohimors** [comment]
I just added a file to ipfs.  It should be available at the following URI but never appears to resolve.  My ipfs version is 0.4.2 (same as the gateway).  I was following the demo, am I missing something?

https://gateway.ipfs.io/ipfs/QmU6ub9mcBtigipmzTZvaZbjmCMgh3aPYHPqi6JzjAQqz4

**Comment by ShariqT** [comment]
I am having this problem as well. Using version 0.4.2

**Comment by ghost** [comment]
Could you try it with the most recent v0.4.3-rc1 from https://dist.ipfs.io?

**Comment by neuronsupport** [comment]
I am using 0.4.4 and have this problem on macosx

**Comment by victorb** [comment]
@norzak are you connected to other peers? You should be able to see that if you run `ipfs swarm peers`. Also, could be that the gateways can't fetch the content for the hash you're trying to load. Do you happen to know where the hash come from and if someone is seeding it?

**Comment by neuronsupport** [comment]
It worked today. I do not know why because I didnt do anything different just run the "ipfs daemon". It must be a glitch at gateway.ipfs.io backend.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/unable-to-retrieve-files-via-gateway-ipfs-io/503

**Comment by g14a** [comment]
Using ipfs version 0.4.12-dev but still face this problem..

I tried doing this to a random text file --> https://gateway.ipfs.io/ifps/Qmbrfhs8a5WVqWzm21BjYi6MggtZrJa5TpHq4LL9tHZZCd

and my localhost says 404 not found. :(

**Comment by Kubuxu** [comment]
@gowtham-munukutla please ask on https://discuss.ipfs.io

**Comment by weihuang1979** [comment]
I m having  this issue . I can see the peers through ipfs swarm peers but when ipfs add a file, the public gateway can't see it. However, when work on an Ali cloud it works. So it should be a Nat problem

**Comment by hatgit** [comment]
This helped for resolving the inability to access your files publicly when they are already uploaded: https://github.com/ipfs-shipyard/ipfs-webui#configure-ipfs-api-cors-headers
