### ISSUE TITLE
Error messages from the daemon

### ISSUE THREAD

**Issue by DavidBooher** [ipfs/support#17]
Version: 0.3.10 
Running OSX and when the webui launches several errors are displayed: 

15:29:52.769 ERROR       mdns: mdns lookup error: failed to bind to any multicast udp port mdns.go:131
18:02:42.755 ERROR       mdns: mdns lookup error: failed to bind to any multicast udp port mdns.go:131
18:05:31.353 ERROR     flatfs: too many open files, retrying in %dms0 flatfs.go:119
18:05:31.365 ERROR     flatfs: too many open files, retrying in %dms100 flatfs.go:119
18:05:31.466 ERROR     flatfs: too many open files, retrying in %dms200 flatfs.go:119
18:05:32.761 ERROR       mdns: mdns lookup error: failed to bind to any unicast udp port mdns.go:131
18:05:32.791 ERROR core/serve: Path Resolve error: open /Users/dbooher/.ipfs/blocks/122029ae/122029aec38245c76eb6e002a025c4163a31bf857a790e2a2ba449f6cfec05a9e71a.data: too many open files gateway_handler.go:458
18:05:32.798 ERROR core/serve: Path Resolve error: open /Users/dbooher/.ipfs/blocks/122029ae/122029aec38245c76eb6e002a025c4163a31bf857a790e2a2ba449f6cfec05a9e71a.data: too many open files gateway_handler.go:458
18:05:32.937 ERROR core/serve: Path Resolve error: open /Users/dbooher/.ipfs/blocks/122029ae/122029aec38245c76eb6e002a025c4163a31bf857a790e2a2ba449f6cfec05a9e71a.data: too many open files gateway_handler.go:458
18:05:33.083 ERROR core/serve: Path Resolve error: open /Users/dbooher/.ipfs/blocks/122029ae/122029aec38245c76eb6e002a025c4163a31bf857a790e2a2ba449f6cfec05a9e71a.data: too many open files gateway_handler.go:458
18:05:33.174 ERROR core/serve: Path Resolve error: open /Users/dbooher/.ipfs/blocks/122029ae/122029aec38245c76eb6e002a025c4163a31bf857a790e2a2ba449f6cfec05a9e71a.data: too many open files gateway_handler.go:458
18:05:33.192 ERROR core/serve: Path Resolve error: open /Users/dbooher/.ipfs/blocks/122029ae/122029aec38245c76eb6e002a025c4163a31bf857a790e2a2ba449f6cfec05a9e71a.data: too many open files gateway_handler.go:458

**Comment by ghost** [comment]
Hey -- we've fixed a couple of ulimit issues ("too many open files") in the past. Please try again with version 0.3.11 from http://dist.ipfs.io, or build from recent master of go-ipfs.

If that doesn't help, try google to find information on how to increase the number of open file descriptors on OSX (keyword: ulimit).

**Comment by howardwu** [comment]
I was able to resolve the issue locally by increasing the open fd count using `ulimit`.

To increase the number of open file descriptors, run `ulimit -n 2560`.
To check that it worked, run `ulimit -a`.
