### ISSUE TITLE
IPFS Socket Address error

### ISSUE THREAD

**Issue by kekw** [ipfs/support#2]
Hi there --

I'm on Linux Mint. Have installed ipfs okay. But am getting this:

Initializing daemon...
ERRO[12:54:20:000] error from node construction: 1: listen tcp6 [::]:4001: socket: address family not supported by protocol
  module=cmd/ipfs
Error: 1: listen tcp6 [::]:4001: socket: address family not supported by protocol

Any ideas? Don't know my way round sockets and things -- is there something I need to install on Linux arount Ports, Sockets, etc.

Thanks, Kek

**Comment by jbenet** [comment]
Should be able to disable IPv6 with:

```
ipfs config --json Addresses.Swarm '["/ip4/0.0.0.0/tcp/4001"]'
```

**Comment by jbenet** [comment]
alt, do `ipfs config edit` and remove the `/ip6/...` line under `Addresses.Swarm`

**Comment by kekw** [comment]
Hi Juan - thanks so much for getting back to me. Sorry for slooow reply; got unexpectedly hit with a bunch of freelance work. I tried using

ipfs config --json Addresses.Swarm '["/ip4/0.0.0.0/tcp/4001"]'

and that worked a treat!

Have now got in okay. Will have a little play and get used to the environment - love the idea of it. I'm intending (hopefully) to host a simple / relative static web-page via IPFS - well, that's the plan. I need to understand the underlying protocol(s), sockets, IPv6, etc. I was never really a web guy. Time for some research.

Thanks for your help.

Cheers, Kek

**Comment by jbenet** [comment]
Thanks for the kind words @kekw -- have fun!

**Comment by kekw** [comment]
No, thank _you_. Got a little 'webpage' thing up on IPFS a couple days ago. Really liking this - will be trying some other things once I wrap my head round it a bit better. Going to try and host an 'album' of music for ppl to download - my own, not someone elses!  :-)

--k
