### ISSUE TITLE
swarm2: swarm listener accept error  WHEN opening ipfs daemon

### ISSUE THREAD

**Issue by chinshiketsu** [ipfs/support#24]
I was following the getting-started steps.
I cannot start up ipfs daemon. Please help me figure out the reason.

$ ipfs daemon
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.122.1/tcp/4001
Swarm listening on /ip4/222.198.155.64/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
09:50:24.048 ERROR     swarm2: swarm listener accept error: peerstream listener failed: accept tcp [::]:4001: use of closed network connection swarm_listen.go:129
09:50:24.048 ERROR     swarm2: swarm listener accept error: peerstream listener failed: accept tcp 0.0.0.0:4001: use of closed network connection swarm_listen.go:129
Error: serveHTTPGateway: manet.Listen(/ip4/127.0.0.1/tcp/8080) failed: listen tcp4 127.0.0.1:8080: bind: address already in use
[chansigit@idrb ~]$ 
Connection closed by foreign host.

**Comment by hackergrrl** [comment]
> Error: serveHTTPGateway: manet.Listen(/ip4/127.0.0.1/tcp/8080) failed: listen tcp4 127.0.0.1:8080: bind: address already in use

It looks like there's another program on your computer that's using port 8080. You can either stop whatever is running on that port (`sudo netstat -tulpn | grep 8080`), or open `${HOME}/.ipfs/config` and change `8080` to some other value.

**Comment by chinshiketsu** [comment]
Thank you very much. I changed the port and it works.
