### ISSUE TITLE
What is "SupernodeRouting" for?

### ISSUE THREAD

**Issue by hshimo** [ipfs/support#25]
I found  "SupernodeRouting" in .ipfs/config. What does this config do?

I'm trying to create ipfs network in private network. Does it affect something to configure private network?

Is it already deprecated and it doesn't do anything?

"No, that feature is deprecated." 
Quote from:
https://groups.google.com/forum/#!topic/ipfs-users/5oEfULoGpt4

**Comment by RichardLitt** [comment]
I'm not sure. @whyrusleeping, do you know?

**Comment by whyrusleeping** [comment]
Yeah, that feature is deprecated and should be removed from the config and codebase.

**Comment by RichardLitt** [comment]
@hshimo Does that answer your question sufficiently? :)

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/what-is-supernoderouting-for/516
