### ISSUE TITLE
Unable to retrieve files via ipfs.io gateway

### ISSUE THREAD

**Issue by ali-aamish** [ipfs/support#26]
I have installed IPFS correctly, but i am unable to retrieve files from ipfs.io gateway or any other gateway it take too much time.

When i use ipfs.pics the gateway fetches files immediately.

The server just sits with a 'Waiting for ipfs.io" message.

Not sure where to start debugging my problem.

**Comment by ali-aamish** [comment]
i am running the same version as gateway i.e: 0.4.1

**Comment by ghost** [comment]
Hey, we'll need a bit more info:
- how are you adding the files?
- does it work with v03x.ipfs.io or v04x.ipfs.io?
- if you didn't add them via your own daemon, but instead e.g. via ipfs.pics -- can you still get them via your local gateway at localhost:8080?

**Comment by ali-aamish** [comment]
i am working on an ipfs application, i added the file using cli and also http api, when i try to fetch the file gateway just sits with a 'Waiting for ipfs.io" message.

it doesn't works with both v03x.ipfs.io and v04x.ipfs.io

but if i add a file through ipfs.pics then i can fetch the file through ipfs gateway and local gateway as well.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/unable-to-retrieve-files-via-ipfs-io-gateway/511
