### ISSUE TITLE
Error: Post http://127.0.0.1:5001/api/v0/add?encoding=json&progress=true&r=true&stream-channels=true: EOF

### ISSUE THREAD

**Issue by karim0028** [ipfs/support#27]
Hi Guys,

Im new to ipfs and trying it out, i was looking to push a static page to the ipfs network and i get this error....

Would love some help in understanding what im doing wrong.

to get this error i did

ipfs add -r <directory>

**Comment by flyingzumwalt** [comment]
In order to provide better support for users we are moving all Help discussions to https://discuss.ipfs.io

If you are still encountering this error, please post it again on https://discuss.ipfs.io
