### ISSUE TITLE
How it can be used to serve content via internet?

### ISSUE THREAD

**Issue by slrslr** [ipfs/support#28]
Hello,

would it be good to mention examples on how the IPFS can be used to distribute content/files over internet/not only via its own network?
Im mainly interested on how IPFS can be beneficial while hosting public webpage on the internet.
But so far cant read any examples on the project webpage and Google find nothing.

**Comment by ghost** [comment]
I've put my static web site files in IPFS, registered an IPNS entry and serve it through an nginx proxy on a VPS.

The relevant config from nginx is: 

```
location / {
  rewrite /(.*) /ipns/graffen.dk/$1 break;
  proxy_pass http://127.0.0.1:8080;
}
```

Does this answer your question?

**Comment by slrslr** [comment]
Thank you, this is what i have been looking for. Also here i found more details on [how to use-ipfs-to-host-your-webpage-using-a-standard-domain](https://github.com/diasdavid/ipscend#use-ipfs-to-host-your-webpage-using-a-standard-domain-includes-cool-dns-trick) and there another tutorial http://www.atnnn.com/p/ipfs-hosting/

Will be there possibility to go round the issue where domain name is the only single point of failure in this system (distributed IPFS ---> cloud hosting server with high availability ---> domain.tld)?

And i assume there is no way regular internet users without IPFS installed can access ipfs pages just via web browser (thanks to for example volunteers who make it somehow accessible)? It is like torrent, but one need torrent client, unless IPFS can be enabled similar way like torrent using WebRTC and [webtorrent](https://github.com/feross/webtorrent) which "enables torrent" even on computers that do not have classic torrent client installed. Maybe if in future, Firefox is made with ipfs://?
https://github.com/nebulis-io/directory

**Comment by hsanjuan** [comment]
Hi, you might be find more details about setting up a website at https://github.com/ipfs/examples/tree/master/examples/websites (this being the official resource on that topic)

About your second comment, the goal is to make the internet better by upgrading the hypermedia distribution system. Not by creating a stack on the side, but by making something that integrates seamlessly (probably unnoticed by the final the user) with the current stack. On this line, work is being done on https://github.com/libp2p/js-libp2p-webrtc-star which will enable the JS implementation of IPFS to use WebRTC for communication and run on the browser. And yes, at some point in the future we would expect browsers to understand `ipfs://` (or `fs://ipfs/...`) and become a node to the ipfs network themselves.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/how-it-can-be-used-to-serve-content-via-internet/508
