### ISSUE TITLE
ipfs warm peers fails

### ISSUE THREAD

**Issue by plungu** [ipfs/support#3]
I have not been able to swarm peers. Except for one time since installing. Not sure how to go about debugging? I've tried 
ipfs swarm connect /ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
I get 
connect QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ failure: dial attempt failed: <peer.ID b2VLNm> --> <peer.ID aCpDMG> dial attempt failed: connection refused

Installed on ubuntu 14.04 using the Linux x86_64 bin

**Comment by jbenet** [comment]
@funngi sorry about this. this has been a problem recently-- we're fixing it and a fix is landing this week. in the meantime you should be able to retry a few times, or try other peers.

@whyrusleeping anything odd with mars?

**Comment by jbenet** [comment]
@funngi same with other peers?

**Comment by plungu** [comment]
Hi @jbenet I tried it on a different network last night and it worked. But I still did not get the Connections screen to come up on the webui. I will try some other peers on the network I was having trouble with. 

btw: just changed my user to plungu

Yeah same with all the peers.

**Comment by jbenet** [comment]
@plungu is this the webui on port 5001? [http://localhost:5001/webui](http://localhost:5001/webui)

**Comment by plungu** [comment]
Yeah http://localhost:5001/ipfs

**Comment by RichardLitt** [comment]
Hey @plungu! Sorry we've been so slow on this. 

Can you replicate this problem, now?

**Comment by kevinmartinmauro** [comment]
Yes, please see https://github.com/ipfs/go-ipfs/issues/2540

**Comment by kevinmartinmauro** [comment]
Okay nevermind, I think it just needed a while to connect to peers?

**Comment by RichardLitt** [comment]
Cool. I'm not sure, either: sorry. If you can't replicate, I'm closing this now, though. Feel free to ping me to reopen! :)
