### ISSUE TITLE
Why can't I access “Hello World!” publicly on IPFS?

### ISSUE THREAD

**Issue by starrychloe** [ipfs/support#30]
http://superuser.com/questions/1096512/why-cant-i-access-hello-world-publicly-on-ipfs

I created a "Hello World!" file and added it to IPFS. 

```
C:\Temp\go-ipfs>ipfs add hello.txt
14 B / 14 B [======================================================] 100.00 % 
added Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z hello.txt

C:\Temp\go-ipfs>ipfs cat Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z
Hello World!
```

However when I try to access it publicly, it locks up and takes forever (longer than 20m).

```
$ curl "https://ipfs.io/ipfs/Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z"
```

> http://ipfs.io/ipfs/Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z

What am I doing wrong? I'm connected to peers.

```
C:\Temp\go-ipfs>ipfs swarm peers | wc
     69      69    5687
```

Even if no one could see me, I would have thought there would be another "Hello World!" file with the same hash somewhere else in the world. 

```
C:\Temp\go-ipfs>ipfs object get Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z
{"Links":[],"Data":"\u0008\u0002\u0012\u000eHello World!\r\n\u0018\u000e"}

C:\Temp\go-ipfs>cat -v hello.txt
Hello World!^M
```

> ipfs version 0.4.2

**Comment by Kubuxu** [comment]
I can see it without any problems:
![](https://gateway.ipfs.io/ipfs/QmUjA74ewQxBV6Qb2u4FHR3omuCebAASz4fTKARHwRZcvV/screencap.2016-07-04T09:58:47Z.png)

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/why-cant-i-access-hello-world-publicly-on-ipfs/507
