### ISSUE TITLE
Can't find peers behind proxy

### ISSUE THREAD

**Issue by morningyyy** [ipfs/support#32]
I can't find any swarm peers.
Is it because I visit the Internet through proxy?
How to config http proxy?

**Comment by jbenet** [comment]
I don't know enough of what's going on on your end to be able to say-- but note ipfs does not use http so it won't follow http proxy settings. depending on setup, it may follow vpn settings, but that's different.

**Comment by jbenet** [comment]
And-- i think the reason this question was not answered in the beginning is that is way too vague. it's hard for us to know what you mean precisely. your description in https://github.com/ipfs/ipfs/issues/209 is better, thanks.

**Comment by pyhedgehog** [comment]
1. "ipfs does not use http"? http proxy has CONNECT method.
2. What about socks configuration? What will be correct format in place of `/ipv4/127.0.0.1/tcp/9050/socks/longandunmemorizablename.onion/QmNODEID`?
3. What about onion bootstrap nodes?

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/cant-find-peers-behind-proxy/514

**Comment by laurasra** [comment]
@flyingzumwalt  What's the point of moving this to a discussion site when there is no official support for it? It really is a support issue.

**Comment by Stebalien** [comment]
> What's the point of moving this to a discussion site when there is no official support for it? It really is a support issue.

This repository has been decommissioned. We've moved *all* support to the forums (discuss.ipfs.io).
