### ISSUE TITLE
Is Neocities online?

### ISSUE THREAD

**Issue by jefft0** [ipfs/support#34]
Neocities web sites have an IPFS multihash. For example, the web site https://neocities.org/site/physicube says it has multihash QmPudMn58sYGZWqW9ZP3MTLEvTP67jddoUqjrNmrzncBni

I started my ipfs daemon (now with 160 peers). In a terminal I entered `ipfs get QmPudMn58sYGZWqW9ZP3MTLEvTP67jddoUqjrNmrzncBni`. But there is no response after five minutes.

Is Neocities part of the IPFS network? Can anyone else get a page from it?

**Comment by Kubuxu** [comment]
Please try using 0.4.3-rc1 from https://dist.ipfs.io

0.4.2 version has serious connectivity problems in case of some types of NAT.

**Comment by jefft0** [comment]
Awesome! Version 0.4.3-rc1 works great. Thanks.
