### ISSUE TITLE
Instead of Filecoin, why not IPFScoin? (using the Graphene blockchain)

### ISSUE THREAD

**Issue by kenCode-de** [ipfs/support#36]
Hi, IPFS newb here, just had a thought. 
I see Filecoin integration with IPFS is in progress, or already done, but why such a slow, unscalable coin? 

If the IPFS community were to run Witness nodes of the Graphene blockchain, then transactions could be set to 3 seconds or less, and could handle 100,000+ transactions per second. 
This would make IPFS unstoppable IMO. 

Here is the code for the graphene chain: 
https://github.com/cryptonomex/graphene 

and the documentation: 
http://docs.bitshares.eu 

Platforms that use a graphene chain of their own: 
Bitshares, Steemit, Muse, Identabit, Peerplays... 

My devs and I are going to start moving all of our libs, api's, websites, even the apk's for our apps onto IPFS starting this next week. 
BlockPay is the largest so far. BlockPay enables any merchant to accept one or more cryptocurrencies at zero cost: 
https://www.youtube.com/watch?v=bcuVSjR6gkk 

We just raised another 900 bitcoins to fund further BlockPay development and IPFS is going to play a huge part in this. 
Would it be possible to skype with a couple of the lead IPFS devs on skype or something? 
I would really like to network a bit closer with you guys and help move this project to heights not yet seen. 

Feel free to contact me any time, please and thank you :) 
  ken 

ken@bitshares-munich.de 
telegram/skype: kenCode_de

**Comment by ghost** [comment]
> start moving all of our libs, api's, websites, even the apk's for our apps onto IPFS starting this next week.

That's great to hear :heartbeat: 

>  I see Filecoin integration with IPFS is in progress, or already done, but why such a slow, unscalable coin? 

We haven't started integrating Filecoin into IPFS yet. IPFS itself will continue to work excellently without Filecoin, and on top of that Filecoin will provide an incentive for adding more and more storage to the IPFS network, and to pay nodes for persistently storing data.

I'd be really interested to hear your feedback on which aspects of Filecoin you think are not scalable, and how that affects IPFS!

**Comment by kenCode-de** [comment]
Here is some other examples of people creating coins on the graphene chain: 
http://cryptofresh.com/assets 

At 100,000+ transactions per second, transactions in 3 seconds or less, and an agile, built-in decentralized exchange, I personally feel like the graphene chain would be the best to start out on. 

Filecoin is not capable of such speeds, scalability, or a decentralized governance system where new features or changes can be decided upon quickly and easily. 

Once we start the IPFS integrations this week, I really need the piece of mind that the "coin" side of this should really consider the graphene chain, as it has so much to offer over any other chain out there. 

As per my contact info above, maybe we could even fenaggle Dan Larimer (the progenitor of the graphene chain) into some guidance on this sweet addition to IPFS. 

Let me know, much appreciated :) 
  ken

**Comment by whyrusleeping** [comment]
> Filecoin is not capable of such speeds, scalability, or a decentralized governance system where new features or changes can be decided upon quickly and easily.

![image](https://cloud.githubusercontent.com/assets/1243164/18232419/06c29eb4-7284-11e6-9303-9c13f7ccacad.png)

**Comment by kenCode-de** [comment]
Compare the Filecoin chain with the graphene chain (specs are all listed above) and you'll see what I mean. If you'd rather choose an inferior chain because it is what you know right now, I understand, but please at least take a look at all of the options that are out there before making final decisions. 

Please understand that I am merely trying to help IPFS to become the unbeatable standard, and world's new protocol for http/ftp upgrade.

**Comment by whyrusleeping** [comment]
Hey @kenCode-de, youre making claims about filecoin without providing any sort of data to back them up. If you have some hard numbers on various aspects of speed and scalability for both chains, i would love to see a side by side comparison. Without that, i'm not sure how you can make the claims you are making. Currently it sounds like pure conjecture and that may very well not be the case, if you have this information I would love to take a look. I'm especially interested in the source of your filecoin performance knowledge.

Thanks!

**Comment by kenCode-de** [comment]
1. What are filecoins block times? 
2. What is the name of the chain that it uses and what chain was it forked from if any? 
3. How many tps is the Filecoin chain capable of?

**Comment by RichardLitt** [comment]
@kenCode-de Filecoin has not been launched yet. You should look at the white paper.

**Comment by Methodise** [comment]
SIA has launched, however. Fully incentivised. http://sia.tech

**Comment by ghost** [comment]
@Methodise stop the spammy behaviour here and in ipfs/faq#207. This is the first warning. See https://github.com/ipfs/community/blob/master/code-of-conduct.md#friendly-harassment-free-space
