### ISSUE TITLE
The docker command is not working unless I add -i parameter

### ISSUE THREAD

**Issue by RyanZhu1024** [ipfs/support#37]
I ran the command from the docker documentation and I got error: ipfs repo not found, please run docker init first. I'm confused by this message as I can't even start the docker, how can I run docker init. So after some other try, I happened to add -i parameter and then it works. I don't know why, but at lease it's working. The command is `docker run -id --name ipfs_host -v $ipfs_staging:/export -v $ipfs_data:/data/ipfs -p 8080:8080 -p 4001:4001 -p 5001:5001 ipfs/go-ipfs:latest` Can someone explain it and maybe update the documentation from the docker up?

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/the-docker-command-is-not-working-unless-i-add-i-parameter/504
