### ISSUE TITLE
Stalling with large file

### ISSUE THREAD

**Issue by hongcoiner** [ipfs/support#38]
Anyone can help try this large file(1.07G) and tell why it's forever stalling at a point after every xxM bytes transferred?

**QmaAg5484aGuTZSGCFyoz3c81cf3XraCgKrrkCyQMinspQ**

No "Block" message found in log but repeating dhtXXXX events after stalling:

...........
":"dhtSentMessage","message":{"key":"QmNQQjXejrWTqcJVn4VvoifyeHVsf2RhiSYYthg3Vr9pcK","type":"ADD_PROVIDER"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","session":"1bf63ad4-e48c-4700-8463-4224cbe9b5fe","system":"dht","time":"2016-09-25T04:12:37.777068986Z"}
{"event":"dhtSentMessage","message":{"key":"QmNQQjXejrWTqcJVn4VvoifyeHVsf2RhiSYYthg3Vr9pcK","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:12:37.778232241Z"}
{"event":"updatePeer","peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:12:37.961336935Z"}
{"event":"dhtReceivedMessage","message":{"key":"","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:12:37.961603242Z"}
{"event":"dhtSentMessage","message":{"key":"QmNR6CfCkGgXozjgrcNeZgBWhBnJXgJWRkGwF6grWU5kUq","type":"ADD_PROVIDER"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","session":"1bf63ad4-e48c-4700-8463-4224cbe9b5fe","system":"dht","time":"2016-09-25T04:13:10.509298528Z"}
{"event":"dhtSentMessage","message":{"key":"QmNR6CfCkGgXozjgrcNeZgBWhBnJXgJWRkGwF6grWU5kUq","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:10.518546515Z"}
{"event":"updatePeer","peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:10.693282081Z"}
{"event":"dhtReceivedMessage","message":{"key":"","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:10.693345958Z"}
{"event":"dhtSentMessage","message":{"key":"QmNRwE1239t9qpB31hY288SpkA4jyAjB4LhaaZPvMNXFCD","type":"ADD_PROVIDER"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","session":"1bf63ad4-e48c-4700-8463-4224cbe9b5fe","system":"dht","time":"2016-09-25T04:13:29.838782603Z"}
{"event":"dhtSentMessage","message":{"key":"QmNRwE1239t9qpB31hY288SpkA4jyAjB4LhaaZPvMNXFCD","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:29.854732199Z"}
{"event":"updatePeer","peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:29.896747759Z"}
{"event":"dhtReceivedMessage","message":{"key":"","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:29.911719038Z"}
{"event":"updatePeer","peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","session":"1bf63ad4-e48c-4700-8463-4224cbe9b5fe","system":"dht","time":"2016-09-25T04:13:33.127104231Z"}
{"duration":3661082,"event":"handleGetProviders","key":"QmPaF1L4YdNRUiKoxPUSS9xpbk9oPjZApRY1YUtWdrp5im","peer":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","session":"1bf63ad4-e48c-4700-8463-4224cbe9b5fe","system":"dht","time":"2016-09-25T04:13:33.131046997Z"}
{"event":"dhtSentMessage","message":{"key":"QmNSEK7NA7i1GKFn4NkFmmpzaetQh52Lv4giWKYHpFWZB6","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:51.313737929Z"}
{"event":"dhtSentMessage","message":{"key":"QmNSEK7NA7i1GKFn4NkFmmpzaetQh52Lv4giWKYHpFWZB6","type":"ADD_PROVIDER"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","session":"1bf63ad4-e48c-4700-8463-4224cbe9b5fe","system":"dht","time":"2016-09-25T04:13:51.327385627Z"}
{"event":"updatePeer","peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:51.42502523Z"}
{"event":"handleGetProvidersBegin","peer":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","session":"1bf63ad4-e48c-4700-8463-4224cbe9b5fe","system":"dht","time":"2016-09-25T04:13:33.127439962Z"}
{"event":"dhtReceivedMessage","message":{"key":"","type":"FIND_NODE"},"peerID":"QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu","system":"dht","time":"2016-09-25T04:13:51.425168232Z"}

**Comment by whyrusleeping** [comment]
@hongcoiner thats interesting... Does it get _some_ of the file? how much progress do you make before it stalls? Also, what version of ipfs are you using?

When it stalls like this, what is the output of `ipfs bitswap wantlist` ?

If you have control of the node that is the original source of the data in question, ensure that the two nodes are connected by checking the output of the `ipfs swarm peers` command for the id of the other node (from `ipfs id`).

Also, if you control the other node, check `ipfs bitswap wantlist -p $STALLED_PEER_ID` to see if that node knows that your stalled peer wants data.

**Comment by hongcoiner** [comment]
Thanks, @whyrusleeping for the hint, what did you see this hash from your side? 
I control the nodes for this experiment, even change to other files with similar size,  every time I met the same issue.

**Comment by hongcoiner** [comment]
I'm trying another file(600M),  **QmTG5KZQF9YnCTnzbcNvevDT5uvhTP81tmfwvWwXWo4ywy**
Seeing the same issue again at 43M. 

checking from source node on $STALLED_PEER_ID(**QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu**):

> ipfs bitswap wantlist -p QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu
> QmRoguowzHtcUoAwRFC2zg9CQQyh5XrEzjByRhciKMiKgt
> QmNnhaKJZmYdW5LtxDs7XQ579wEVhkwtx83UTNgFxPiirQ
> QmW28WA3HLupgzKD8S1Cjx4tbQmBrqhMkUpt6V7aaboj2V
> QmcnD2Uar9dAFiyDCCrx61KViiqWzPqwPJ5LrPJQJaHFSk
> QmQuEdJVwKRhXk6ZxQx94z76jXAPUr3X1tMakhFVZiLhxb
> QmfEVhDchSnvMPqqyXLNCCb3YtHp1WahXH4vVYZHoina3q
> QmUf1TKp2TPmeZVvMmMUYueSy3BXzcNgneh67TXTXXzzzt
> QmbDGY8VpVA53T4hRKCAaYA3vxrbBhrwbRP3SAyUNoFZMe
> QmZU2FscQmPjsy5wrSCoJP9fuqxj8z4F5k71B7WiHbmBUW
> QmUVwmBcwdf7Cm1d4KzNgZ4qJDRmdUy29nKrL1112maJEk
> QmTSvPc3tTtJc6eQDzm4QCm1B2WRS6trXMoEmh6rKCbDi8
> Qmb8LuK7R5884qanRLEKezG98NYA4Hgg3z76YiEvHvEmJ7
> QmTYSExnKgrQLgRG6MGb65UfoDHjGhNr6PvLa13UYSQWD7
> QmebAUTcz4EPZxpb4Mxxxi92VbYQJqo4waXk5agZGY9e19
> QmbqymDGKcAeQnZv9APmpXLhUAsAAEHNCbh2DQDFXPRq3D
> QmSXZbmbPXPHK2bxFy5C36pCKC9kF2QZXQNyAbo6z9aGbb

Means there's data demand from destination peer, 
If I run:

> ipfs swarm peers|grep QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu
> /ip4/192.168.0.117/tcp/4001/ipfs/QmcH1YhjYUCd6B8Zu2qYKNNYxqQ3BcXKGVU194CW7goqGu

There's such peer in list, how to dig in depth?

**Comment by hongcoiner** [comment]
It's solved by upgrading to the most recent version v0.4.3
