### ISSUE TITLE
unable to update to ipfs 0.4.0

### ISSUE THREAD

**Issue by stuffyvater** [ipfs/support#40]
Hi i'm trying to update ipfs using the ipfs-update command. I get the following output:

```
krisnaer@krisnaer-VirtualBox:~$ ipfs-update
ipfs-update: command not found
krisnaer@krisnaer-VirtualBox:~$ ipfs update
Error: %!s(MISSING) not installed.
```

Did i misunderstand something or should this not update to the latest version?

**Comment by ghost** [comment]
You need to install `ipfs-update` before you can run the `ipfs update` command: https://dist.ipfs.io/#ipfs-update

**Comment by stuffyvater** [comment]
when running: go get -u github.com/ipfs/ipfs-update
i get : package context: unrecognized import path "context" (import path does not begin with hostname)

Is this because go is not set up properly?

**Comment by dignifiedquire** [comment]
What version of `go` are you using? This sounds like it needs `go 1.7`

**Comment by stuffyvater** [comment]
```
go version go1.6.2 linux/amd64
```

readme says 1.5 or higher https://github.com/ipfs/ipfs-update/blob/v1.3.0/README.md

**Comment by dignifiedquire** [comment]
`go-ipfs` does require 1.7, so this might propagate. You can also just download the binary here https://dist.ipfs.io/#ipfs-update

**Comment by stuffyvater** [comment]
I downloaded the binary and installed it following this [linux forum tutorial](http://www.linuxforums.org/forum/linux-tutorials-howtos-reference-material/64958-how-install-software-linux.html) I get this output:

 krisnaer@krisnaer-VirtualBox:~/go-ipfs/ipfs-update$ make install
cat install.sh >install 
chmod a+x install

I then run the updater:

 krisnaer@krisnaer-VirtualBox:~/go-ipfs/ipfs-update$ go get -u github.com/ipfs/ipfs-update
package github.com/ipfs/ipfs-update: cannot download, $GOPATH not set. For more details see: go help gopath 

I'm guessing i need to set this up? Will read into doing this, thank you for all your help for now!

**Comment by stuffyvater** [comment]
Since I need to make a pitch using IPFS on Monday I will probably not update now that it works, but would like to figure out how afterwards... seems to be getting Golang to work which is preventing it...  Thank you for your help!
