### ISSUE TITLE
Decentralizing an app with IPFS/IPNS 

### ISSUE THREAD

**Issue by kenCode-de** [ipfs/support#41]
Hey, I know this isn't really a place to advertise but I need your IPFS knowledge here. I am decentralizing an app (it's also a module in ERP app stores) and using IPFS to do it, so this is a rather large project that I could really use some assistance with if you can help me, and/or to get the word out, please. 

I posted the job on Coinality here: 
https://coinality.com/jobs/ipfs-guru-wanted/ 

Please help me spread the word, this IPFS/IPNS job begins immediately. 
Thanx in advance,
  ken

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/decentralizing-an-app-with-ipfs-ipns/510
