### ISSUE TITLE
Slow getting files

### ISSUE THREAD

**Issue by yxliang01** [ipfs/support#47]
So, I have two computers running IPFS daemon. When I add one file on one computer and ipfs get on the other computer, it seems to take forever! However, when I visit https://ipfs.io/ipfs/HASH then my computer gets it immediately. I can understand that it's because the file is being provided by one of the bootstrap nodes which acts as a bridge. However, I feel like the file finding process should be able to be faster? Thanks and Merry Christmas.

**Comment by hsanjuan** [comment]
Can you provide more details? are the two computers in the same network? do they see each other (`ipfs swarm peers`)?

If they are in the same network and they don't see each other, you can try finding out why (mDNS blocked somehow?) etc. you can always manually connect them with `ipfs swarm connect`.

**Comment by yxliang01** [comment]
Well, so, at first, they don't see each other. Then, they found each other and started transferring. What I wanted to say is kinda because of slow peer discovery if I analysed correctly.

**Comment by xloem** [comment]
I'm having this issue (can get files off the web but not from command line, just hangs), where both machines are behind a firewall.  They are not in `ipfs swarm peers` and when I `ipfs swarm connect`, it just gives me `failure: dial attempt failed: context deadline exceeded`.

Is there perhaps a special way to craft a multiaddr for a firewalled peer?

**Comment by xloem** [comment]
Turns out one machine must not be firewalled.

**Comment by yxliang01** [comment]
Because of firewall, there's no way for them to communicate with each other because IPFS doesn't support node as relay?

**Comment by xloem** [comment]
https://github.com/ipfs/faq/issues/202 is related

**Comment by yxliang01** [comment]
I see! I think that's it. If anyone doesn't think it is, just reopen this issue.
