### ISSUE TITLE
Cannot transfer between two firewalled machines

### ISSUE THREAD

**Issue by xloem** [ipfs/support#48]
Does ipfs allow transfer between two machines, neither of which will accept incoming connections?

I seem to be able to view the files on gateway.ipfs.io, but not retrieve them from the commandline.

`ipfs get` just hangs for a long time.  `ls -l /ipfs/[hash]` gives `ls: cannot access /ipfs/[hash]/[file]: No such file or directory`.

**Comment by xloem** [comment]
To answer my own question: no, ipfs does not support this.

Open port 4001 if you want to share files with others.
If you are firewalled and want to download a file from a machine that is firewalled, visit the file on gateway.ipfs.io first, so that it has a non-firewalled source.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/cannot-transfer-between-two-firewalled-machines/505
