### ISSUE TITLE
stop/quit/halt/shutdown ipfs daemon

### ISSUE THREAD

**Issue by jbshirk** [ipfs/support#5]
somewhere it should say what is the proper way to shut down ipfs, for example, to do an update.

**Comment by jbenet** [comment]
for go-ipfs: like other unix processes: sending it the `kill` signal will shut it down, if it hangs send it again (will skip graceful shutdown) or send `kill -9`

**Comment by whyrusleeping** [comment]
noooo, `kill -9` is bad!! two `SIGTERM`s will do the job just fine!

**Comment by jbshirk** [comment]
I'll bet one day ipfs will want a graceful, polite shutdown.

**Comment by jbenet** [comment]
agreed

**Comment by almereyda** [comment]
"And I am always waiting, for the last log line never to disappear."

Could the shutdown message itself propose to the user to issue `SIGTERM` again, if it's taking too long?

**Comment by RichardLitt** [comment]
Opened an issue about it, because I agree that this really ought to be somewhere in the descriptions itself.
