### ISSUE TITLE
Error: cannot acquire lock when running ipfs cat

### ISSUE THREAD

**Issue by liymax** [ipfs/support#50]
$ ipfs cat /ipfs/QmPnnvFkvSCmPvMdMtSNbXrFWQX5XYc4YkcVU4cujyyH8Z/readme
Error: cannot acquire lock: file "C:\\Users\\10667\\.ipfs\\repo.lock" already locked

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/error-cannot-acquire-lock-when-running-ipfs-cat/519
