### ISSUE TITLE
How to config centos to start ipfs automatically ?

### ISSUE THREAD

**Issue by beyonderyue** [ipfs/support#52]
I want start ipfs automatically after power on..  but I met issues like belows:
The ipfs daemon start automatically, but after 1min, it is terminated.
Mar 01 10:52:27 acw5.localdomain ipfs[1373]: Swarm listening on /ip4/127.0.0.1/tcp/4001
Mar 01 10:52:27 acw5.localdomain ipfs[1373]: Swarm listening on /ip6/::1/tcp/4001
Mar 01 10:52:27 acw5.localdomain ipfs[1373]: API server listening on /ip4/0.0.0.0/tcp/5001
Mar 01 10:52:27 acw5.localdomain ipfs[1373]: Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8090
Mar 01 10:52:27 acw5.localdomain ipfs[1373]: Daemon is ready
Mar 01 10:53:55 acw5.localdomain systemd[1]: ipfs.service operation timed out. Terminating.
Mar 01 10:53:55 acw5.localdomain ipfs[1373]: Received interrupt signal, shutting down...
Mar 01 10:53:55 acw5.localdomain ipfs[1373]: (Hit ctrl-c again to force-shutdown the daemon.)
Mar 01 10:53:56 acw5.localdomain systemd[1]: Failed to start ipfs.
Mar 01 10:53:56 acw5.localdomain systemd[1]: Unit ipfs.service entered failed state.

**Comment by whyrusleeping** [comment]
@beyonderyue what does your ipfs.service file look like?

**Comment by beyonderyue** [comment]
@whyrusleeping 
[Unit]
Description=ipfs
After=network.target

[Service]
Type=forking
ExecStart=/usr/local/bin/ipfs daemon
ExecReload=
ExecStop=
PrivateTmp=true

[Install]
WantedBy=multi-user.target

**Comment by Kubuxu** [comment]
@beyonderyue ipfs daemon does not fork. For sample good service file see: https://aur.archlinux.org/cgit/aur.git/tree/ipfs.service?h=go-ipfs-git

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/how-to-config-centos-to-start-ipfs-automatically/515
