### ISSUE TITLE
Running ipfs api on https

### ISSUE THREAD

**Issue by shayzlufsynereo** [ipfs/support#54]
Can I run ipfs api on https?
How do I configure it?

**Comment by lidel** [comment]
AFAIK HTTPS is not supported by `go-ipfs`. 
You need to use [TLS termination proxy](https://en.wikipedia.org/wiki/TLS_termination_proxy) (eg. Nginx, HAProxy, etc).

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/running-ipfs-api-on-https/497
