### ISSUE TITLE
how to get back my peer identity hash

### ISSUE THREAD

**Issue by inauman** [ipfs/support#56]
Hello -

I am new to IPFS and just installed it. After I did "ipfs init", I got my peer identity hash and it was working fine. But once i closed that window, I don't know how to get back the has of my public key?

I checked the "ipfs config show" but the PeerID displayed is different from the Peer Key which i received with "ipfs init" and the command like "ipfs /ipfs/peer key/readme" doesn't work...

Can you please advise how I can get the same hash key which was generated during "ipfs init"?

**Comment by hsanjuan** [comment]
`ipfs id`?

> I checked the "ipfs config show" but the PeerID displayed is different from the Peer Key which i received with "ipfs init" 

Should be the same...

**Comment by inauman** [comment]
Hello -
Sorry, it was my mistake...Peer ID is same what got generated and what I see using "ipfs id" command...
