### ISSUE TITLE
Pinning does not happen concurrently but in sequence...

### ISSUE THREAD

**Issue by matthiasbeyer** [ipfs/support#57]
(Pasting this here because I'm not sure whether it belongs to)

#### Version information:

go-ipfs version: 0.4.8-
Repo version: 5
System version: amd64/linux
Golang version: go1.8

#### Type:

Bug, unexpected behaviour

#### Severity:

Medium

#### Description:

If I run `cat hashes | while read h; do ipfs pin add "$h" & done` or `ipfs pin add` (so it reads from stdin) and paste a list of hashes into stdin, it seems to try these hashes in sequence rather than concurrently (what would be the expected behaviour).

Because of this I failed to pin ~25 hashes for the last 3 days. Just because the very first hash couldn't be fetched. All others seem to work now...

**Comment by Kubuxu** [comment]
`< hashes | ipfs pin add -` might work better.

ipfs pin add works in serial as for pin lock.

@lgierth can we resolve it somehow? We don't need to hold pin lock while fetching.

**Comment by ghost** [comment]
Workaround for now is a round of `ipfs refs -r <hash>` (which works concurrently too) and then the pin round.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/pinning-does-not-happen-concurrently-but-in-sequence/496
