### ISSUE TITLE
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080

### ISSUE THREAD

**Issue by Bowfish** [ipfs/support#58]
If I start the ipfs daemon it starts in readonly mode. How can I start it in read and write mode?

API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready

**Comment by ghost** [comment]
Set `"Gateway.Writable": true"` in `ipfs config edit`, or start the daemon with `ipfs daemon --writable`

**Comment by ghost** [comment]
Please reopen if this didn't help
