### ISSUE TITLE
ipfs daemon problem/bug with enabled RansomWhere by ObjectiveSee

### ISSUE THREAD

**Issue by JayBrown** [ipfs/support#59]
This is probably a general bug, so I'm posting it here.

When installed, [**RansomWhere?**](https://objective-see.com/products/ransomwhere.html) by **ObjectiveSee** watches for rapid encryption processes on the local volume. This apparently happens from time to time with `ipfs`. Until the user allows the encryption process to continue, RansomWhere will stop the parent ipfs process, but this seems to be "too much" for the daemon, which will be interrupted almost immediately, but not quit, so if you try to restart the daemon, ipfs will tell you that it's already running, even though there was some kind of interrupt, because the shell prompt is available again for the user. So the only remedy is to `killall ipfs` and restart the daemon.

I guess there would need to be a little ipfs tweak, in that ipfs will wait (with a timeout?), if a different process has halted/stopped (but not killed) ipfs.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/ipfs-daemon-problem-bug-with-enabled-ransomwhere-by-objectivesee/502
