### ISSUE TITLE
Where can I send a crash stack dump?

### ISSUE THREAD

**Issue by bdimych** [ipfs/support#61]
recently I created ipfs service on my vps and left it running,
now I checked the vps and see that ipfs was running 5 days and then crashed with "fatal error: runtime: out of memory"

and now there is a large stack dump in the /var/log/messages:
/var/log/messages-20170507:May  7 00:25:11 etologichno ipfs: fatal error: runtime: out of memory
/var/log/messages-20170507:May  7 00:25:11 etologichno ipfs: runtime stack:
/var/log/messages-20170507:May  7 00:25:11 etologichno ipfs: runtime.throw(0xdb63dc, 0x16)
/var/log/messages-20170507:May  7 00:25:11 etologichno ipfs: /home/whyrusleeping/go/src/runtime/panic.go:596 +0x95
/var/log/messages-20170507:May  7 00:25:11 etologichno ipfs: runtime.sysMap(0xc4524b0000, 0x100000, 0x400, 0x146d078)
/var/log/messages-20170507:May  7 00:25:11 etologichno ipfs: /home/whyrusleeping/go/src/runtime/mem_linux.go:216 +0x1d0
/var/log/messages-20170507:May  7 00:25:11 etologichno ipfs: runtime.(*mheap).sysAlloc(0x1453f80, 0x100000, 0x7f7e414b0b10)
/var/log/messages-20170507:May  7 00:25:11 etologichno ipfs: /home/whyrusleeping/go/src/runtime/malloc.go:428 +0x374
/var/log/messages-20170507:May  7 00:25:11 etologichno ipfs: runtime.(*mheap).grow(0x1453f80, 0x2, 0x0)
/var/log/messages-20170507:May  7 00:25:11 etologichno ipfs: /home/whyrusleeping/go/src/runtime/mheap.go:774 +0x62
/var/log/messages-20170507:May  7 00:25:11 etologichno ipfs: runtime.(*mheap).allocSpanLocked(0x1453f80, 0x2, 0x7f7e414b0b10)
...
etc
very large log - 539 Kb

where I can send this log to?
or I just shouldn't?

**Comment by hsanjuan** [comment]
Hi! Please refer to https://github.com/ipfs/go-ipfs/issues/3532 as this is probably related (is it a small VPS?)
