### ISSUE TITLE
Is the a "recommended" (by common sense) waiting time for "ipfs get" if it hangs for too long?

### ISSUE THREAD

**Issue by Katamori** [ipfs/support#63]
Given the very early phase of the project and the slightly torrent-like p2p nature, it is expectable that not every file has 0-24 accessibility in the network.

Still, as someone who **really** wants to see IPFS in large-scale and/or truly practical use, I find it outstandingly inconvenient that several files is either not even started to be downloaded (percentage bar not showing up) indefinitely, or if started, suddenly halts at certain points, without giving me the chance to contribute and pin it.

As of mid-May 2017, what is the time I can/should wait for hanging "get" processes before deciding to give up on them?

It's especially important because I run my IPFS node on AWS and CPU usage is limited - and "ipfs get" is a processor-heavy command, according to `top -o %CPU`.

**Comment by flyingzumwalt** [comment]
This issue was moved to https://discuss.ipfs.io/t/is-the-a-recommended-by-common-sense-waiting-time-for-ipfs-get-if-it-hangs-for-too-long/500
