### ISSUE TITLE
Found link that tell us to report issues here

### ISSUE THREAD

**Issue by jota-rv** [ipfs/support#67]
Hi, I encountered a link that is telling to report issues here, it can be found at: https://flyingzumwalt.gitbooks.io/decentralized-web-primer/content/ under the **Getting Help** section.

**Comment by flyingzumwalt** [comment]
Thanks for catching that @jota-rv -- I fixed it!

**Comment by abitrolly** [comment]
Not fixed here - https://dweb-primer.ipfs.io/
