### ISSUE TITLE
Raspberry Pi 2 and IPFS opens as IPV6 no matter what network I am connected to

### ISSUE THREAD

**Issue by deawar** [ipfs/support#7]
Hi,
Loving the permanent web idea! Want to setup lowpower Raspberry pi's to create my own local swarm, but when ever I IPFS init I get IPV6 addresses that it is trying to listen on and I have no IPv6 to connect to. How can I configure IPFS for only ipv4 so I can use the daemon to connect to the local swarm and to the global swarm?

Thanks in advance. BTW I have dropped this on both my local LUG(Linux users groups) and any others I can get to so we can get as many nodes up as possible in the next few weeks.

**Comment by jbenet** [comment]
thanks!

remove the `/ip6/...` address inside of the `Addresses.Swarm` array in the config. see `ipfs config --help` and `ipfs config edit`.

**Comment by jbenet** [comment]
> Thanks in advance. BTW I have dropped this on both my local LUG(Linux users groups) and any others I can get to so we can get as many nodes up as possible in the next few weeks.

thanks very much! please direct any questions and problems over here or to `#ipfs` on IRC :)

**Comment by deawar** [comment]
Dude,
Thank you for answering my silly nOOb question. I am in awe of this project!

**Comment by jbenet** [comment]
Thanks! :) help us make it even better! \o/ we have much cool stuff in progress.

—

**Comment by RichardLitt** [comment]
@deawar Feel free to reopen as needed! :)
