### ISSUE TITLE
webui not showing node info, connections in 0.3.10-dev

### ISSUE THREAD

**Issue by HoboPrimate** [ipfs/support#8]
Just downloaded the Linux X86_64 version off the main website, and overwrote the old version located at /usr/local/bin and deleted ~/.ipfs and initted.

The webui doesn't show node info or connections, although 'swarm peers' shows connections and no errors appear in the terminal.

**Comment by jbenet** [comment]
@HoboPrimate it's important to include the hash of the WebUI you're seeing

**Comment by jbenet** [comment]
@HoboPrimate please look at your javascript console in your browser and see if there are any errors.

**Comment by HoboPrimate** [comment]
This is strange, now it's working!
Could it be that it had the old webui cached somehow in the browser? Although I did try the hash you gave me on irc, and it still wasn't working.

**Comment by HoboPrimate** [comment]
sorry for the confusion I created! Keep up this awesome work!

**Comment by HoboPrimate** [comment]
I'm reopening this issue because I saw someone new on irc also not getting information about connections from the webui, and after I restarted the node, as well.
There are a bunch of these javascript errors in the browser's console:

403 - Forbidden
["/Users/jbenet/git/ipfs/webui/js/pages/home.jsx"]</Home<.getInitialState/<() bundle.js:1141
requestAPI/req</<() bundle.js:51239
["/Users/jbenet/git/ipfs/webui/node_modules/browserify/node_modules/events/events.js"]</EventEmitter.prototype.emit() bundle.js:7551
["/Users/jbenet/git/ipfs/webui/node_modules/browserify/node_modules/http-browserify/lib/response.js"]</Response.prototype.handle() bundle.js:8236
["/Users/jbenet/git/ipfs/webui/node_modules/browserify/node_modules/http-browserify/lib/request.js"]</module.exports/xhr.onreadystatechange() bundle.js:7999

I'm using firefox.

**Comment by HoboPrimate** [comment]
It started working after a reboot !

**Comment by jbenet** [comment]
So this should be closed, right? reopen if not.
